---
title: "What the TEch Sector Indicates about our Economy"
author: "Alexis Rivera-Andrade"
date: "5/21/2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#This is attaching files for the tech sector

DataProject <- read.csv("FinalDatafornow.csv", header = TRUE)
attach(DataProject)
View(DataProject)
TechEffect <- lm(SFTECH ~ Unemp + CapUtil + Dis.IncPerCap + PPI
                 + RecessionIndic, data = DataProject)

SFTECH.ts <- ts(SFTECH, start = c(1972,1), frequency = 12)

```


TechPulse  =  \(\beta_1\) + Unemp\(\beta_2\) + CapUtil\(\beta_3\) + Recession\(\beta_4\) + DIncome\(\beta_5\) + \(\beta_6\)
#This is attaching files for the tech sector



```{r cars, echo = TRUE}
plot(SFTECH.ts, col = "blue", ylab = "Index Jan 2000 = 100", main = "U.S. Tech Sector")
rect(1973+11/12,0, 1975+3/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
rect(1980+1/12,0, 1980+7/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
rect(1981+7/12,0, 1982+11/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
rect(1990+7/12,0, 1991+3/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
rect(2001+3/12,0, 2001+11/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
rect(2007+12/12,0, 2009+6/12, c(-30,250), col=rgb(160,160,160, maxColorValue=255, alpha=100),
     border=F)
box()
```


#VIF
```{r}
vif(TechEffect)
```

#Summary Statistic
```{r pressure}
summary(TechEffect)
```

